Adding HZAU
project-trans/RLE-wiki pull request #101
Opened 2023-03-30 16:33 UTC by RimuroSuraimu

Content created for review. 

Content quality is limited as information submitted is limited for review.

2023-03-30 16:42 UTC, RimuroSuraimu commented
Resovlved #44

2023-03-30 17:27 UTC, Cryolitia requested changes
辛苦了喵

2023-03-30 17:27 UTC, Cryolitia commented on docs/campus/HZAU.md
> +### 概况
top-level 标题请使用 ``##``

2023-03-30 17:27 UTC, Cryolitia commented on docs/campus/HZAU.md
> +学校有早操要求， 大一大二住宿舍的必须出操，有人查宿舍。
建议添加换行
```suggestion
学校有早操要求， 大一大二住宿舍的必须出操，有人查宿舍。

同时有体育课的学期环湖跑计入，不达圈数即挂科。
```

2023-03-30 17:27 UTC, Cryolitia commented on docs/campus/HZAU.md
> +蔡赵天 beta_cai@webmail.hzau.edu.cn
```suggestion
蔡赵天 <beta_cai@webmail.hzau.edu.cn>
```

2023-03-30 17:27 UTC, Cryolitia commented on docs/campus/HZAU.md
> +> 规模大概能有几十个人，但很多人并没有在各种 QQ 群和微信群里紧密联系。由于有 purple 这个性少数社团，所以很容易能和一群友好的人们建立联系。总体环境不错。
奇奇怪怪的一句话……

2023-03-31 00:07 UTC, Rinfair-CSP-A016 commented
修改意见同上

2023-03-31 01:40 UTC, Cryolitia approved these changes

2023-03-31 05:30 UTC, merged