河北工业大学：适配新贡献模板，重构和简化
project-trans/RLE-wiki pull request #114
Opened 2023-06-02 02:55 UTC by LiMee233

还需共同商量修改，不着急

发现模板有些问题：

1. LGBT 友善梗概，可能和院系探路重复
2. 投稿人联系方式和贡献者姓名重复
3. 体测很重要，应该在模板中有所添加

2023-06-02 06:08 UTC, HalfSweet commented
感谢您的意见，现已更新模板且修改您的贡献中的相关描述。
关于体测的部分，您可以参考<https://github.com/project-trans/RLE-wiki/blob/feature/SchoolContributionTemplate/docs/contributor-guide/CampusTemplate.md#%E4%BD%93%E6%B5%8B>最新的模板进行修改。

2023-06-02 14:38 UTC, Nickel-Angel requested changes
体育课在秋季学期体育课选课期间或春季学期体育课开课后 1 周内向体育部提交书面申请，就可以通过相关医院开具“不适宜运动”的证明来改为保健课，并且可以申请到体测免测。
但是对开证明的医院的要求模糊不清，学生手册上写的是“学校指定的医院”和校医院需同时开具证明。
在春季学期，有的老师会在前几节体育课上提醒需要转保健课的同学提交材料，但是由于个人没有详细了解，需要详细咨询辅导员和体育老师。

2023-06-02 14:38 UTC, Nickel-Angel commented on docs/campus/HEBUT.md
> +### 人工智能与数据科学学院 2021 级的一位 MtX
建议直接写 Nickel_Angel 这样？

2023-06-02 14:44 UTC, LiMee233 commented on docs/campus/HEBUT.md
> +### 人工智能与数据科学学院 2021 级的一位 MtX
已修改

2023-06-02 14:45 UTC, Nickel-Angel approved these changes

2023-06-02 14:48 UTC, LiMee233 commented
> 体育课在秋季学期体育课选课期间或春季学期体育课开课后 1 周内向体育部提交书面申请……

凡是能开具「不适宜运动证明」应该在绝大多数学校都不成问题；此信息无法直接解决 MtF 是否能使用病例、诊断证明或者 HRT 处方申请保健课和免测的问题，驳回

2023-06-02 18:02 UTC, Cryolitia commented
@LiMee233 以普遍理性而论，一般需要随便一个什么诊断然后医生在病历上写一句不适宜剧烈运动

2023-06-13 15:38 UTC, Cryolitia commented
请问这个分支现在的情况是可以合并还是等待进一步修改，如果仍需修改请标记为draft

2023-06-13 23:06 UTC, LiMee233 commented
无明显问题，目前可以合并。

2023-06-14 03:13 UTC, Cryolitia approved these changes

2023-06-14 06:26 UTC, HalfSweet approved these changes

2023-06-26 16:23 UTC, merged