Update UCAS.md
project-trans/RLE-wiki pull request #125
Opened 2023-06-26 23:29 UTC by dawn-moon

2023-06-27 05:13 UTC, HalfSweet approved these changes

2023-07-02 07:06 UTC, Cryolitia requested changes

2023-07-02 07:06 UTC, Cryolitia commented on docs/campus/UCAS.md
> +> ~~正在建成中国跨学院大学中~~ 人数虽然不多但trans比例不低，除了已知trans外经常会遇到性别表达中性的疑似TGD群体
这里的TGD是什么意思喵

2023-07-02 07:06 UTC, Cryolitia commented on docs/campus/UCAS.md
> +更新：前往精神专科医院就诊无需开具转诊单，可直接凭发票、处方笺和明细单报销。易性症病名报销可能会稍微困难，不知道磨一下校医能否成功（因此有adhd和抑郁症等极度利好报销）。可将医生开具的绝大部分检查转至精神专科医院（如回龙观）进行，包括六项检查在内都可报销。美容成型科开具的激素似乎不能报销。刘烨的内分泌科处方报销问题同易性症（而且需要开具转诊单，更为麻烦）。
更新两个字不用写在正文里面

2023-07-02 07:06 UTC, Cryolitia commented on docs/campus/UCAS.md
> +关于学习情况。随意转专业是个优点，但注意有挂科记录后就无法转至计算机系。课程设置很难但平时成绩占比很大，考试基本都会放水捞捞所以只要作业都交基本不会挂科。如果有adhd尽量早点开药不要拖欠作业酿成大祸（x
ADHD改一下大写喵

2023-08-23 09:48 UTC, merged