add: 武汉科技大学
project-trans/RLE-wiki pull request #128
Opened 2023-07-01 05:32 UTC by XiangYyang

* 添加了武汉科技大学的一些概况

2023-07-01 05:33 UTC, HalfSweet approved these changes

2023-07-02 07:14 UTC, Cryolitia requested changes

2023-07-02 07:14 UTC, Cryolitia commented on docs/campus/WUST.md
> +|      宿舍独卫      |  -  |  黄家湖校区北一到北十仅在每层设有数个公共卫生间，黄家湖校区北十一到北十四有独卫，南一至南十有待补充，但每层楼依然设有数个公共卫生间。青山校内宿舍没有独卫，每层设有两个公共卫生间。学四学五情况未可知。人和公寓（截至2023年度，人和公寓依然是启用状态）有独卫  |
过长的备注建议写在下方正文喵

2023-07-02 07:14 UTC, Cryolitia commented on docs/campus/WUST.md
> +正体育课在大一大二开设，按照男女生理性别分开，内容较多且一些考核简单，可以选并不困难的课程（具体可咨询自己的学长学姐们，这里不涉及具体的任课老师）。体育课还开设的有所谓的保健班，针对体质不好的学生，但是具体情况本人不清楚。
「正体育课」是什么喵

2023-07-02 13:46 UTC, HalfSweet approved these changes

2023-07-05 00:10 UTC, Cryolitia approved these changes

2023-07-05 00:11 UTC, merged