Update NJU.md
project-trans/RLE-wiki pull request #160
Opened 2023-09-08 04:46 UTC by njujimbo

第一次用github还不太熟悉，请多指教~(￣▽￣)~*

2023-09-08 05:09 UTC, BeiyanYunyi requested changes

2023-09-08 05:09 UTC, BeiyanYunyi commented on docs/campus/NJU.md
> +如果想得到较为专业的hrt指导或者开证的话，可以坐高铁去宛平南路600号/上海九院。
开证在南京有曹秋云和武欣，开证难度都比陆峥低，别想不开去上海精卫。

这一行可以考虑直接链接 MtF.wiki 长三角页面。

2023-09-08 05:09 UTC, BeiyanYunyi commented on docs/campus/NJU.md
> +如果想得到较为专业的hrt指导或者开证的话，可以坐高铁去宛平南路600号/上海九院。
然后 markdown 里面单纯换行是不会被渲染成换行的。你可以试着这样子：

```
第一段

第二段
```

效果：

第一段

第二段

或者：

```
第一段\
第二段

第一段  （注意左边这里有两个空格）
第二段
```

效果：

第一段\
第二段

第一段  
第二段

两种方式的区别是，前者分段，后者只是单纯换行

2023-09-08 05:15 UTC, BeiyanYunyi requested changes

2023-09-08 05:15 UTC, BeiyanYunyi commented on docs/campus/NJU.md
> +如果想得到较为专业的hrt指导或者开证的话，可以坐高铁去宛平南路600号/上海九院。
```suggestion
本人实测呢喃校医院不能做激素六项（差评），最近似乎是要坐178路去仙林鼓楼医院，价格大概一两百，详细流程和体验等我最近有空空去看看回来更新（

补佳乐校医院的价格不清楚，不过我在和园最西边的那家药店买过，27.8一盒，不算太贵，而且很好买，不需要任何处方也不会问你用途。

如果想开证，可以在南京找[武欣](https://mtf.wiki/zh-cn/docs/psyco/jiangsu/wu-xin/)（需要在读证明）或[曹秋云](https://mtf.wiki/zh-cn/docs/psyco/jiangsu/cao-qiuyun/)（需要家长同意）。

如果需要较为专业的 hrt 指导，建议前往[上海](https://mtf.wiki/zh-cn/docs/hrt/shanghai/)。
```

2023-09-08 08:39 UTC, HalfSweet commented on docs/campus/NJU.md
> +author: Lhcfl njujimbo 等
多个作者的话，需要写成类似这样的多行结构：
```yaml
author: 
     - Lhcfl 
     - njujimbo 
```

需要注意的是，这里使用的是`yaml`语法，因此请注意缩进的层级

2023-09-08 09:18 UTC, BeiyanYunyi commented on docs/campus/NJU.md
> +author: Lhcfl njujimbo 等
```suggestion
author: 
  - Lhcfl
  - njujimbo
  - 等
```

2023-09-08 10:11 UTC, septs commented on docs/campus/NJU.md
> +如果想得到较为专业的hrt指导或者开证的话，可以坐高铁去宛平南路600号/上海九院。
我认为不应该提供公交信息，毕竟考虑到公交线路运营是一个市场化行为

提供 POI 及挺勤时间预期是相对合理的

2023-09-08 10:53 UTC, BeiyanYunyi approved these changes

2023-09-08 12:34 UTC, njujimbo commented
我还需要做什么呀，看rle.wiki还是修改之前的样子没有变

2023-09-08 12:37 UTC, njujimbo commented
我还需要做什么呀，看rle.wiki还是修改之前的样子没有变

2023-09-08 12:46 UTC, BeiyanYunyi commented
这个 pr 还没 merge，merge 之后才能看见效果的喵

2023-09-08 12:46 UTC, septs commented on docs/campus/NJU.md
> +这里是其中一位笔者，github:njujimbo,twitter:@njujimbo,qq:1169253331,一位23届环院今年刚毕业但最近会随机出没于校内麦当劳等地的学长（如果看见某书包上有粉色螺旋挂件就是我捏），是一位成分纯正的友跨（暂时还没翻车），如果大家有打算建群可以戳我或者拉我，以后有机会说不定还可以一起去周围面姬捏~(￣▽￣)~*
虽然开放的态度很好，但是这样的信息可能导致**反跨人士**通过这个对你的生活产生影响

注意安全

2023-09-08 12:59 UTC, njujimbo commented
<img width="690" alt="image" src="https://github.com/project-trans/RLE-wiki/assets/144367787/02418d97-1451-4c1d-a989-8c3433da7391">
需要我/管理员怎么做吗

2023-09-08 13:14 UTC, merged

2023-09-08 13:24 UTC, HalfSweet commented
@njujimbo 非常抱歉，您的`投稿人联系方式`格式有误，我们将revert您的这次pr，您可以重新开启这个pr并进行修改

建议的修改如下
```markdown
## 投稿人联系方式

### njujimbo
这里是其中一位笔者，这是我的联系方式：
- github: [njujimbo](https://github.com/njujimbo)
- twitter: [@njujimbo](https://twitter.com/njujimbo) 
- qq:1169253331

我是一位23届环院今年刚毕业但最近会随机出没于校内麦当劳等地的学长（如果看见某书包上有粉色螺旋挂件就是我捏），是一位成分纯正的友跨（暂时还没翻车），如果大家有打算建群可以戳我或者拉我，以后有机会说不定还可以一起去周围面姬捏~(￣▽￣)~*
```

2023-09-08 23:35 UTC, Cryolitia commented
@HalfSweet 别revert啊

2023-09-08 23:40 UTC, Cryolitia commented on docs/campus/NJU.md
> +本人实测呢喃校医院不能做激素六项（差评），最近似乎是要坐178路去仙林鼓楼医院，价格大概一两百，详细流程和体验等我最近有空空去看看回来更新（
呢喃是typo还是整活

2023-09-08 23:40 UTC, Cryolitia commented on docs/campus/NJU.md
> +如果需要较为专业的 hrt 指导，建议前往[上海](https://mtf.wiki/zh-cn/docs/hrt/shanghai/)。
hrt 全大写

2023-09-09 02:06 UTC, njujimbo commented on docs/campus/NJU.md
> +本人实测呢喃校医院不能做激素六项（差评），最近似乎是要坐178路去仙林鼓楼医院，价格大概一两百，详细流程和体验等我最近有空空去看看回来更新（
我们学校喜欢这么自称（