add: 添加江南大学
project-trans/RLE-wiki pull request #172
Opened 2023-09-17 14:33 UTC by HalfSweet

2023-09-17 14:37 UTC, BeiyanYunyi approved these changes

2023-09-17 19:27 UTC, RimuroSuraimu requested changes
最好增加最基本的地理位置还有交通相关信息，currently >>todo<<

2023-09-25 01:09 UTC, AnotherReader commented
> 最好增加最基本的地理位置还有交通相关信息，currently >>todo<<

done，btw学校似乎可以视为只有主校区

2023-10-01 02:52 UTC, Cryolitia approved these changes

2023-10-02 07:29 UTC, merged