add: 中国传媒大学
project-trans/RLE-wiki pull request #178
Opened 2023-09-29 07:57 UTC by Master-Hash

2023-09-29 08:11 UTC, BeiyanYunyi requested changes

2023-09-29 08:11 UTC, BeiyanYunyi commented on docs/campus/CUC.md
> +要求打卡长跑（“阳光长跑”），男生 2.4km ，女生 2.0km，每学期7周之内完成15次即满分，至少7次可以有成绩。可以使用自行车作弊，校园墙上也有“指导”。（有趣的是，来抓你的不是体育老师而不是）（闺蜜大四的五一节，就“指导”了无数人，戏称“阳光长征”）
（有趣的是，来抓你的不是体育老师而不是）

这句好像有点问题，是说“来抓你的是 xx 而不是体育老师”吗

2023-09-29 08:14 UTC, CoelacanthusHex commented on docs/campus/CUC.md
> +要求打卡长跑（“阳光长跑”），男生 2.4km ，女生 2.0km，每学期7周之内完成15次即满分，至少7次可以有成绩。可以使用自行车作弊，校园墙上也有“指导”。（有趣的是，来抓你的不是体育老师而不是）（闺蜜大四的五一节，就“指导”了无数人，戏称“阳光长征”）
「而不是」后面是不是漏了内容。

2023-09-29 09:46 UTC, BeiyanYunyi approved these changes

2023-10-01 02:51 UTC, Cryolitia approved these changes

2023-10-01 14:14 UTC, merged