添加中国农业大学信息
project-trans/RLE-wiki pull request #200
Opened 2023-10-29 12:28 UTC by mcxufly

2023-10-29 12:54 UTC, BeiyanYunyi requested changes

2023-10-29 12:54 UTC, BeiyanYunyi commented on docs/campus/CAU.md
> +:::
```suggestion
```

这个是给贡献者看的标注，要删去

2023-10-30 01:08 UTC, mcxufly commented on docs/campus/CAU.md
> +:::
已接受更改

2023-10-30 07:14 UTC, mcxufly commented
已接受更改

2023-10-30 13:16 UTC, BeiyanYunyi approved these changes

2023-10-30 13:19 UTC, BeiyanYunyi requested changes

2023-10-30 13:43 UTC, mcxufly commented
已接受更改

2023-10-30 13:55 UTC, BeiyanYunyi approved these changes

2023-10-31 08:39 UTC, HalfSweet approved these changes

2023-10-31 08:40 UTC, merged