Update THU
project-trans/RLE-wiki pull request #204
Opened 2023-11-11 12:35 UTC by ZenithalHourlyRate

2023-11-11 12:45 UTC, BeiyanYunyi requested changes

2023-11-11 12:45 UTC, BeiyanYunyi commented on docs/campus/THU.md
> +清华因为有不同时间修建的宿舍，所以会出现比较复杂的情况。紫荆公寓（本科），四人间，每两间之间有个中厅，男生宿舍厕所大概每 8 间一个的公共厕所有小便池和隔间，浴室也是大概每 8 间一个的大概有 3 个淋浴头的公共浴室。然后是南区宿舍，也是 4 人一间，没有中厅，是最新的宿舍，有独立浴室，相对私密性会好一些。然后是不同的研究生公寓，硕士生与低年级直博生住老楼，为三人间，一层楼两个公共浴室，每个喷头
```suggestion
清华因为有不同时间修建的宿舍，所以会出现比较复杂的情况。紫荆公寓（本科）为四人间，每两间之间有个中厅，男生宿舍厕所大概每 8 间一个的公共厕所有小便池和隔间，浴室也是大概每 8 间一个的大概有 3 个淋浴头的公共浴室。然后是南区宿舍，也是 4 人一间，没有中厅，是最新的宿舍，有独立浴室，相对私密性会好一些。然后是不同的研究生公寓，硕士生与低年级直博生住老楼，为三人间，一层楼两个公共浴室，每个喷头有隔板与门，厕所也是公共厕所，有小便池与隔间；普博生与高年级直博生住两人间，W 楼（紫荆博士公寓，14-17 号楼，在学校最北边）为两人间，有独立卫生间，两间屋共用一个阳台，以及双清公寓，为两人间，在校外，具体情况不清楚。
```

这一段不太通顺，有歧义，我的理解可能有误。酌情考虑改一下

2023-11-11 12:45 UTC, BeiyanYunyi commented on docs/campus/THU.md
> +[^1]: 甲类完全报销，乙类按比例报销，丙类全自付。类似于没有起付线、封顶线，报销比例 100% 的医保。自杀产生的医疗费用不予报销。
黑色幽默）

2023-11-11 13:04 UTC, BeiyanYunyi commented
其实不用 force push 啦，merge 的时候会 squash 的

2023-11-11 13:05 UTC, BeiyanYunyi approved these changes

2023-11-12 04:57 UTC, HalfSweet approved these changes

2023-11-12 04:57 UTC, merged