Update BJTU.md
project-trans/RLE-wiki pull request #248
Opened 2024-01-30 12:19 UTC by 0-394642

笔者为2023级学生，此次修改主要增加了对办理保健班、校医院资源以及LGBT友善度的描述，并优化了部分表达。

2024-01-30 12:30 UTC, BeiyanYunyi approved these changes

2024-01-31 13:08 UTC, Cryolitia requested changes
Markdown中如需使最终渲染结果换行请空一行，否则请写在完整的一行中。在Markdown中仅换行没有意义。

2024-01-31 13:08 UTC, Cryolitia commented on docs/campus/BJTU.md
>  补充：
```suggestion
> 可以申请走读。走读分保留宿舍与不保留宿舍两种，后者需要签保证书与父母同意。学校宿舍较老旧，如有条件建议走读。

补充：
```

2024-01-31 13:08 UTC, Cryolitia commented on docs/campus/BJTU.md
> +一般而言大一学生上课需要两个校区来回，步行15分钟左右，可购买自行车（校内共享单车不出校，校外共享单车不入校）。
```suggestion
学校共有东校区和主校区两个校区，二者相距约 1 公里。大一学生大部分住在东校区，而大二至大四的学生会住在主校区。

一般而言大一学生上课需要两个校区来回，步行15分钟左右，可购买自行车（校内共享单车不出校，校外共享单车不入校）。
```

2024-01-31 13:08 UTC, Cryolitia commented on docs/campus/BJTU.md
> +报销力度与北京的市属高校接近，低于部分央属高校，但报销原则较为宽松。具体报销项目范围可以在学校官网查询。
```suggestion
公费医疗，可转诊北京大学人民医院（骑车15分钟可达），北医三院（亲测三院HRT可以报销）与18家专科医院。

需要先开转诊后报销，但实测校医院医生开转诊较为宽松，可以以其他内分泌疾病为由转诊北医三院内分泌科。

报销力度与北京的市属高校接近，低于部分央属高校，但报销原则较为宽松。具体报销项目范围可以在学校官网查询。
```

2024-01-31 13:08 UTC, Cryolitia commented on docs/campus/BJTU.md
> +据校外某医生所说，校内有多名 MtF，但尚未发现有MtF群/线下面基等活动。
```suggestion
笔者所在的是数学与统计学院，感觉对LGBT整体包容程度较高。同学们在心理班会上以同性恋开玩笑很正常，笔者也曾公布过自己性取向不明，同学们都较为接受。\

据校外某医生所说，校内有多名 MtF，但尚未发现有MtF群/线下面基等活动。
```

2024-02-04 04:35 UTC, 0-394642 commented
@Cryolitia 本人第一次发起 Pull request，请问如此修改可以吗？为何显示 partially verified?

2024-02-04 05:36 UTC, Cryolitia approved these changes
可以的

2024-02-07 08:13 UTC, merged

2024-02-26 10:49 UTC, Incises commented
@0-394642 you can send an email to me. see my profile ;-)