打算上传一个写有自己所有RLE经验的系列文档
project-trans/RLE-wiki pull request #285
Opened 2024-03-12 18:46 UTC by Ethanlita

得到了大学时代一个木桶饭朋友的建议而写的，目前只有大纲和一点点内容，主要内容是分享经验。
全部写完必然需要很长时间，会慢慢写。
如果RLE.wiki愿意收录的话，请不要立刻合并，但是欢迎在这里提出建议。
如果不愿意收录的话，请关闭这个拉取请求，我还会继续写完并发到其他地方。

2024-03-12 19:31 UTC, clansty commented on docs/fashion/a-guide-to-a-welcomed-girl/social.md
> +# 0x01.A 不要整天喵喵喵！
感觉看着不太舒服捏

为什么要让我们改变现有的自己舒服的方式而去靠近一个刻板印象的「女生」

RLE 的目的不是探索自己舒适的方式，让自己靠近自己的内心吗

2024-03-13 02:52 UTC, BeiyanYunyi commented
先写着吧，我想 rle wiki 应该是能放下的。

2024-03-13 10:11 UTC, LittleSound commented
我们刚刚更新了 main 分支，因此你会看到现在的的 PR 中有很多不属于你的 commit。
可以请你通过 git rebase main 更新一下分支么。非常感谢。

2024-03-14 06:48 UTC, Ethanlita commented on docs/fashion/a-guide-to-a-welcomed-girl/social.md
> +# 0x01.A 不要整天喵喵喵！
这个只是个人经验，观点并不能保证适合每一个人
但我认为普通女生的社交模式有助于提升心理健康，这样的指引可以帮助减少一些内耗和迷茫。
更何况，女生的社交圈不等于全部成员都是刻板印象的女生，扩展自己的社交圈也不能说是靠近刻板印象。
同时考虑到，实际上我们或许也有很多人的内心期待就是成为刻板印象的女生呢？（比如我）
基于这样的考量，我认为这是必要的

当然了，距离写到这个地方或许还需要很长时间……（因为虽然有大纲，但是光是写一章头发就已经很费心思了，之后化妆和衣服的章节只会更多QWQ）
最后内容写出来如果不合适再修改，或者关掉这个拉取请求也是可以的
（毕竟我想，第一次合入时这里无论如何也要完成40%以上吧？几个月的时间还是需要的啦）

2024-03-14 08:30 UTC, Ethanlita commented
已经进行了rebase，主分支的commit已经合入

2024-03-14 08:50 UTC, BeiyanYunyi commented on docs/fashion/a-guide-to-a-welcomed-girl/tutorial.md
> +**你好，初次见面，我是丽塔。** 我和绝大部分看到这里的你们一样，我们都是跨性别女生——没错，就是那种遗传学上应当属于男性，但是认同自己是女生的情况。
其实“遗传学”这个词并不是一般认为的那么确定的。“X/Y 染色体”仍然只是一种表象，一个人带或不带 Y 染色体就认为 ta “遗传学上应该是 x 性”其实不那么恰当。Y 染色体上只有 SRY 基因与性别有关，SRY 在表达过程中还需要其他基因的协同作用，中间任何一个环节的不同都会带来（心理、出生时生理）性别的不同。因此，能决定出生时生理性别的因素有非常非常多，包括嵌合体、超雌、部分或完全雄不敏等。

也因此，“指派性别”才是更准确的用词：出生时，社会（家长和医生）根据你的第一性征所接近的那个性别，认为你将来的性别角色是什么。

“顺性别者”也会因为错误的指派性别而出现性别焦虑。例如 [David Reimer](https://en.wikipedia.org/wiki/David_Reimer) 在婴儿时期就因为在包皮手术中阴茎被毁而被指派为女，从幼年开始出现性别焦虑，经历了 HRT、SRS ~~和自杀~~的跨性别者全流程。因此，跨性别就其本质而言是一种处境，跨性别者的定义就是“指派性别与性别认同不同”。

当然这里就是说一下，不改也没事~~反正这里包容度还挺大的~~）

2024-03-14 09:09 UTC, Ethanlita commented on docs/fashion/a-guide-to-a-welcomed-girl/tutorial.md
> +**你好，初次见面，我是丽塔。** 我和绝大部分看到这里的你们一样，我们都是跨性别女生——没错，就是那种遗传学上应当属于男性，但是认同自己是女生的情况。
好，改

2024-03-14 11:32 UTC, LittleSound commented
> 已经进行了rebase，主分支的commit已经合入

多了一条 Commit：[Merge next into main](https://github.com/project-trans/RLE-wiki/pull/285/commits/f00518a1dbd936accda1207e668bc84445ab068f)

你可以用 `git rebase -i main` 来进入交互式变基，在这个模式下你可以选择并删除多余的提交

2024-03-14 15:59 UTC, Ethanlita commented
好像我原本就是交互式的rebase，应该是哪里操作失误了（指按错了），明天电脑上重新做一次（反正纯纯加新文件应该没有冲突）@LittleSound

2024-03-28 03:28 UTC, Ethanlita commented
是写完一个章节就进行一次合并比较好，还是全部写完再合并比较好？

2024-03-28 04:51 UTC, BeiyanYunyi commented
> 是写完一个章节就进行一次合并比较好，还是全部写完再合并比较好？

我觉得都可以，你看看怎么样比较好吧

2024-04-10 13:42 UTC, Cryolitia commented
您好，请问这个分支现在已经完工了嘛，我看您已经上传了后记和结尾

2024-04-10 13:51 UTC, Ethanlita commented
还没有呢，您可以看到还剩下很多很多没有完成的部分。一小时后我可能会push一个提交到lita分支，那是我这边的最新进度。还有另一位作者在nico分支上写作，但她不知道什么时候会提交。
你可以先review已经提交的部分，如果想要合入的话也可以，但是在最终完成以前这些东西都是as is的

2024-04-10 13:55 UTC, Cryolitia commented
好的，辛苦您了。

另外，您可以不用处理ci相关的问题，这部分我们会在部署前调整。

> 这句话是给其他editor看的：内容review完毕就可以合并，合并前调整base到staging分支；在staging分支调整部署后merge进主分支。

2024-04-10 14:01 UTC, Ethanlita commented
谢谢您
我把ci的工作流删掉是因为每次push那个东西都要报错，这边看合入前我会处理那个问题的

2024-04-10 14:02 UTC, Ethanlita commented
我看了我这fork的项目没有测试环境的env，因此那个pipeline报错是没办法的

2024-04-10 14:14 UTC, Cryolitia commented
> 我看了我这fork的项目没有测试环境的env，因此那个pipeline报错是没办法的

![image](https://github.com/project-trans/RLE-wiki/assets/23723294/8d439477-a32f-47e8-a65b-e5975c5e2b99)

您可以在您自己的fork中把setting里的action关掉，把这个页面设成disable就可以

2024-04-10 14:17 UTC, Ethanlita commented
![7c41d98b9f223bf51e24c1ec9c11af51_720](https://github.com/project-trans/RLE-wiki/assets/65023676/a179ab21-259c-4f23-a9c7-cdc83869b184)
![50700ec40fe2a25c423352c073cf905f_720](https://github.com/project-trans/RLE-wiki/assets/65023676/61741998-b644-41d5-aae1-e3892f956960)
今天我有位朋友（也是作者的一员）找到了这样的图，为此我加了一个宇宙安全声明，项目成员这边对于这张图里的讨论是什么态度呢？

2024-04-10 14:33 UTC, Ethanlita commented
这边已经更新了最新的进度到主分支

2024-04-10 14:39 UTC, Cryolitia commented
好的，辛苦了。

diff里有个多出来的 `.github/worflows/next.yml` 辛苦删一下

https://github.com/project-trans/RLE-wiki/pull/285/files#diff-e9ff79014fe3225c85eca733ca7a5800a4ac3fcdb715b16792f45fb36aa1c8c2

2024-04-10 14:44 UTC, Cryolitia commented
> 今天我有位朋友（也是作者的一员）找到了这样的图，为此我加了一个宇宙安全声明，项目成员这边对于这张图里的讨论是什么态度呢？

对于这个问题我们有官方回应：
![image](https://github.com/project-trans/RLE-wiki/assets/23723294/ecf4b0d4-e63d-4fcc-9772-2296d93d3262)

我认为，RLE.wiki的定位并不是仅仅面向MtF群体的RLEwiki，而是面向所有跨性别者和其他性少数群体的RLE.wiki，每个人的作品都是整个多元化群体的一个切面而不能代表整个群体，描绘了如何成为作者自己希望成为的样子（而不是MtF应该成为的样子）。下一步我们会尽量丰富这个栏目的稿件内容，使内容更加多元化。

2024-04-10 14:48 UTC, Ethanlita commented
好的，已经push了更改

2024-04-10 14:52 UTC, Ethanlita commented
好的，回应我看到了，谢谢您。之前加入的宇宙安全声明是我们的立场，就先姑且保留好了

2024-04-11 03:13 UTC, clansty commented on docs/fashion/a-guide-to-a-welcomed-girl/tutorial.md
> +作者团的全员都是支持女性主义和女性平等独立的。事实上，作为跨性别女生，我们更加能够体会到女性在社会中的困境，所以我们更加支持女性主义。如果换成更加赤裸裸的说法，那就是，我们无法通过我们在生育方面的价值在男权社会中交换到任何利益，因此我们事实上没有任何理由不支持女性的平等和独立。
我觉得不要扯上这些东西吧

最好是不要扯上“女性主义”之类的东西

也没有明确“女性主义”的定义是什么

我自己也讨厌这些东西

而且，说“体会到女性在社会上的困境”的时候，我体会到的是跨性别比女性更困得多的困境

所以我感觉比起关注普通的“女性困境”我更关注跨性别困境

普通的女性困境在跨性别的困境前面已经不算什么了

而且很多“女性主义”的人的观点是和跨性别的利益冲突的

2024-04-11 14:07 UTC, Cryolitia commented on docs/fashion/a-guide-to-a-welcomed-girl/tutorial.md
> +作者团的全员都是支持女性主义和女性平等独立的。事实上，作为跨性别女生，我们更加能够体会到女性在社会中的困境，所以我们更加支持女性主义。如果换成更加赤裸裸的说法，那就是，我们无法通过我们在生育方面的价值在男权社会中交换到任何利益，因此我们事实上没有任何理由不支持女性的平等和独立。
女性主义实际上是一个非常复杂的议题，其包含了许多复杂冲突的派别（部分派别支持跨性别和酷儿运动，部分部分反对），「通过生育价值在男权社会交换价值」这类表述容易使人产生不当联想，从而招致部分派别的女性主义者的反对，不建议在RLEwiki过多涉及此类议题。

且此段叙述内容过于情绪化，可能会给读者带来不好的阅读体验，适得其反的造成更糟糕的后果。建议将表述修改为更温和的叙述如「作者团的全员都支持女性的平等独立」。

政治议题CC @project-trans/invited-experts 邀请发表专业意见。

2024-04-11 14:31 UTC, jinyuzu99 commented
建議更中性的表達：性別平權On Apr 11, 2024, at 22:08, 北雁 Cryolitia ***@***.***> wrote:﻿
@Cryolitia commented on this pull request.



In docs/fashion/a-guide-to-a-welcomed-girl/tutorial.md:
> +
+本系列文档的目的是帮助你更好地渡过转换时期。但是，每个人的终点都是不一样的。
+
+有的人只想进行一部分的转换，而希望社会接纳她们带着剩下的不那么符合女孩子刻板印象的部分，并且在社会生活中将她们视为女生。
+
+这很好，我要说，这没有什么问题。我在这里向每一位读者保证，包括我在内的所有作者都不会因为你的选择而对你有任何不好的看法，不会明示或者暗示你要符合刻板印象中的女孩子形象。
+
+本系列文档中的任何内容，如果你确信你不喜欢那样做，那就绝对不要那样做。这并不是什么金科玉律，只是一些建议。对于我们来说，如果你希望被社会接纳为女生，也许你需要变得符合刻板印象中的女孩子形象，但是这并不是必须的，女孩子也具有非凡的多样性，只不过你可能需要另一种被社会接纳的方法罢了。
+
+我们的目的是帮助你更好地过渡，而不是强迫你成为一个你不想成为的人。
+
+但是因为包括我在内的作者团中的大家的愿望是成为“受欢迎的女孩子”“普通的女孩子”“放到人堆里不会被挑出来的女孩子”，换言之就是“符合社会刻板印象的女孩子”，所以本系列文档的写作是以此为基准的。
+
+---
+
+作者团的全员都是支持女性主义和女性平等独立的。事实上，作为跨性别女生，我们更加能够体会到女性在社会中的困境，所以我们更加支持女性主义。如果换成更加赤裸裸的说法，那就是，我们无法通过我们在生育方面的价值在男权社会中交换到任何利益，因此我们事实上没有任何理由不支持女性的平等和独立。

女性主义实际上是一个非常复杂的议题，其包含了许多复杂冲突的派别（部分派别支持跨性别和酷儿运动，部分部分反对），「通过生育价值在男权社会交换价值」这类表述容易使人产生不当联想，从而招致部分派别的女性主义者的反对，不建议在RLEwiki过多涉及此类议题。
且此段叙述内容过于情绪化，可能会给读者带来不好的阅读体验，适得其反的造成更糟糕的后果。建议将表述修改为更温和的叙述如「作者团的全员都支持女性的平等独立」。
政治议题CC @project-trans/invited-experts 邀请发表专业意见。

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are on a team that was mentioned.Message ID: ***@***.***>

2024-04-11 16:24 UTC, Ethanlita commented
已经合入了修改

2024-04-11 22:50 UTC, Cryolitia commented on docs/fashion/a-guide-to-a-welcomed-girl/tutorial.md
> +我们支持性别平等，但是我们也希望自己能够被社会接纳，所以我们会尽力去做到符合刻板印象的女生。
提醒各位重点review这一段

2024-04-12 00:46 UTC, P-ZH requested changes

2024-04-12 00:46 UTC, P-ZH commented on docs/fashion/a-guide-to-a-welcomed-girl/tutorial.md
> +> 我们认为，女性的性别气质是有一定的合理性的，因为女性的性别气质是由女性的生理特征决定的，而生理特征是与生俱来的。
即便是性别认同为女的人，也有大把人不是

> 头发相对男性更长
> 脸部线条相对男生更加柔和
> 声音相对男生频率更高

你可以说你喜欢这些，并且这些对你作为女性的性别认同很重要。你也可以说社会主流对女性有一些外貌上的期待，对于想被社会认可为女性的群体（尤其是一直以来被排斥在「女性」这一领域之外的人来说），策略性地迎合这些期待，对于满足「想被社会认为是女性」这一欲望是有作用的。但你肯定不能说这些「性别气质」是「合理的」并且有「生理基础」…总之我上面改了。

2024-04-12 04:53 UTC, clansty commented
放化妆教程，修头发教程什么的可以
别放什么社会规训教程
也别放什么女权教程
也不要指导别人的价值观和思考方式
我们不应该指导别人的想法，而是指导别人如何实现自己的想法
只应该放细分方面的教程

2024-04-12 05:00 UTC, clansty commented
以及我觉得可以教的只有物理的东西，比如如何改变外观。而不包括无形的东西，比如怎么交朋友，因为这一定有主观观点。也不应该包括如何实现“某个定义”的东西，比如说如何变可爱，因为你不能说，只有这样才是可爱，那样了就不可爱

2024-04-12 05:06 UTC, Mak1owo commented
我觉得本篇中包含了太多的「观点」性的内容，有一些我能认可，有一些我持怀疑态度。朋友们的对这些观点也各有各的看法。这让我思考一个问题：

> RLE Wiki 是什么？RLE Wiki 到底应该做什么？

我认为 RLE Wiki 应该保持其中立性，不应该被用来输出观点，无论这个观点被项目维护方支持或是反对 —— 而应该作为一个能包容各种观点，能给各种不同人的合理诉求提供指导的地方。

我的建议是，把本篇中的观点性内容全部移除，把各种实践性内容打散，以中立性的语言来描述每一件具体的「如何怎么怎么样」，并且在项目维护方认为「这种行为可能有争议」的章节开头标明 disclaimer，确保读者不会被作者的观点所影响。

2024-04-12 05:07 UTC, Ethanlita commented
我正在通知其他作者来阅读你们提出的建议。
然而，这些建议很有可能不会被全部接受，因为确实改变了我们的观点。但是基于对于不同的人的心理健康的考虑，我们会在不改变我们的观点的基础上对具体的语言进行一些调整。
我们会在十几个小时后更新这个拉取请求

2024-04-12 05:15 UTC, clansty commented
> 因为确实改变了我们的观点

你不需要观点，你只需要实际的教程。想发观点可以去推特发

2024-04-12 05:19 UTC, Mak1owo commented
引申出来另一个我想到的问题 ——

> 写出「输出争议性观点的」内容的作者一定是有意的吗？可能未必。

很多人受限于人生阅历和生活环境，并不能（或者没有意识）去站在中立的视角上去叙事，他们可能认为「这个世界就是这样的」。我希望审校者们能够意识到，并且理解作者的这种行为。本篇中就有很多「无意中带着观点」的表述，比如，跨性别语境下「真正的女孩子」就是一个典型的例子。

我希望，审校者能够了解各种观点，在遇到（无论有意地还是无意地）持与自己相悖的观点时，能够站在作者的观点视角上去理解作者想要说明的事情，提出修改建议，必要时需要大段的改写（也许 LLM 能帮上忙），而不是一味的对观点相悖的表达进行批判 —— 我认为本项目作为一个「实践指南」并不是一个用来争论观点的地方。

2024-04-12 05:34 UTC, Ethanlita commented
（这个comment是我的观点，未经其他作者的同意）
其实我是能感觉到你们有在很矛盾的，特别是在前两天的事件过后，我看到了你们的声明，所谓的只是一个切面而非全貌就是如此。
我觉得我们比你们想得更清楚，我们无法得到每一个人的认可。
但实际上你们一边说着这只是一部分人，一边却要求要（也许）每个人都能接受的官方观点。

实际上没有观点是不可能的，我们无法做到。或者换言之，在这些文档中每一句话都是观点。
并且，正如这个拉取请求的标题所述，这是我们的个人经验。最初是我的个人经验，但是现在有了其他作者的加入，她们也会提供她们的经验。

为什么我的大学同学会期待我写一个很完整的经验文档？那是因为我的RLE简直是成功的没边了，如果不考虑自谦的问题，在跨性别女生中就没有几个能比我融入得更好的。（我们其他作者也属于融入比较好的人）难道你们真的觉得rle只是改变形象的事情？如果我只想写一些普通的，不带我的特色的东西，那这个系列的文档将根本不会存在（毕竟，那样的东西谁都可以写）

说实话，我是很久没有见过系统性的这类指南了。那本《好想做个女孩子——伪娘养成手册》是在我初中的时候进入我的百度网盘的，非常遗憾。但是这么多年了仍然有很多人在看那个。mtf.wiki上面的内容至今为止仍是漏洞百出，rle.wiki上的内容更是少得可怜。实际上自从那本手册以来，我是很久都没有见到过一本完善的，成体系的，内容跟得上时代的手册了。

说实话，这些内容只不过是我们决定对这个群体的一些贡献，我个人并不奢望每个人都要喜欢它，但是这是我们的经验。我们选择了rle.wiki只是因为这个网站看起来比较美观，功能还算好用罢了。
>想发观点可以去推特发
如果你们认为是这样的话，我们就真的去其他地方发了。并且我们会在后续版本中标注“本系列内容根据知识共享许可协议向除了project-trans项目有关的任何实体授权”。
以上，请各位reviewer重新考虑是否要撤回前面的commit

2024-04-12 05:39 UTC, P-ZH commented
@Mak1owo 我觉得困难的地方就在这里：实践性内容总是包含着作者理解这些实践的方式和进行这些实践的目的，而这往往就会呈现为你所说的「观点」。目前的投稿都是大家对自己 RLE 经验的总结，融入个人视角也很正常；如果按照所谓「要女身先女心」的古早说法来看，对 rle 的预先理解反而是 rle 成功的基本条件。

在这个意义上，我对这种「中立性」是否真的有可能通过像用「LLM 大段修改」达到表示疑惑，毕竟 LLM 也是在很多问题上有明确立场或倾向的。也同样是因为这个原因，我认为 rle.wiki 为其内容或网站本身设立一些基本伦理原则并没有问题；当然，这些原则的内容可以讨论。

我在 comment 的时候确实带了很多个人观点，但我的核心考虑其实是舆情：即，当我们提起「女权主义」这个词的时候，我们事实上是在做一件招魂的事情，它很可能导致许多自认为和这个词相关的人都来凑热闹，而我们任何关于这个词语不够审慎的表述，都可能成为被用来攻击我们的子弹。我的 comment 也仅仅是在女权主义相关的那个段落作出的；对于别的部分，我想只要 rle wiki 能保证内容上足够高的多元程度，不同 rle 方案作者在观点上的差异是不需要进行干预或调整的。

2024-04-12 05:44 UTC, clansty commented
> 那是因为我的RLE简直是成功的没边了

如何定义成功呢，你觉得的成功可能别人不一定觉得。而且你觉得你得到了成功的同时，很可能你也因此舍弃了一些东西

> 难道你们真的觉得rle只是改变形象的事情

虽然很可能不是，但是在 wiki 上我们应该只需要改变形象相关的教程。形象以外的东西，每个人都有自己的认知，不应该传授观点而是应该鼓励人们自行探索

> 就没有几个能比我融入得更好的

虽然这可能是你想要的，但不一定是其他人想要的。并且这样的说辞会给人一种高高在上（privilege）的感觉，使人不适

> 非常遗憾。但是这么多年了仍然有很多人在看那个

请不要同时贬低别人的作品。更不要在不接受别人说自己的作品不好的同时说别人的作品不好

> 如果你们认为是这样的话，我们就真的去其他地方发了

你可以在这里发表非观点性质的教程，但是至少我不接受灌输观点性质的内容。你可以投稿那部分具体细分的教程到 RLE Wiki。我们也不奢求“系统性的 RLE 教程”。如果你希望发表大量观点性质的东西，你可以自行发布。发布和以后可能收到的评价都和 Project-Trans 没有关系

2024-04-12 05:46 UTC, Cryolitia commented
@Ethanlita 那是因为我的RLE简直是成功的没边了，如果不考虑自谦的问题，在跨性别女生中就没有几个能比我融入得更好的。（我们其他作者也属于融入比较好的人）难道你们真的觉得rle只是改变形象的事情？如果我只想写一些普通的，不带我的特色的东西，那这个系列的文档将根本不会存在（毕竟，那样的东西谁都可以写） 

建议他们把整个pr投稿清蒸和esuwiki

2024-04-12 05:48 UTC, Ethanlita commented
> 你可以在这里发表非观点性质的教程，但是至少我不接受灌输观点性质的内容。 
@Cryolitia  这是一个整体，我们无法彻底将其分割。
> 建议他们把整个pr投稿清蒸和esuwiki
请自便

好了，现在你们可以关闭这个拉取请求了。

2024-04-12 05:50 UTC, sauricat requested changes
RLE 是让人以所认同性别的方式生活，不是让人融入顺性别。
那些你掺杂个人同化价值的东西不建议合并。 @P-ZH 的参考意见已经很具体了，我基本同意。

2024-04-12 05:51 UTC, clansty commented
关的好呀，刚还想说请求关闭此 PR 呢

2024-04-12 05:52 UTC, Cryolitia commented
先都冷静一下

2024-04-12 06:17 UTC, clansty commented
我觉得别锁了
不用锁（

2024-04-12 07:16 UTC, closed without merging

2024-04-12 08:45 UTC, BeiyanYunyi commented
1. 善意提醒：CC 协议似乎并不支持“向除了 xx 以外的实体授权”，协议是英文形式的法律条文，无法较为简单地进行额外修改。尽管 project trans 不太可能在未来使用此内容，但如果你确实希望排除 project trans，那么你应该使用别的协议而非 CC。
2. 推荐发布到论坛，在几个论坛中，我已与 futarino 的管理员沟通过，对方表示欢迎。
3. 如果你需要自建网页，我可以以个人名义协助。

2024-04-12 08:50 UTC, Cryolitia commented
@Ethanlita

**GitHub是面向所有人开放的代码平台**，而不是RLE.wiki专用的审稿平台，**任何人都能自由的在上面发表观点**，这也是我们保持开放合作的基石。首先向你明确一下参与讨论的人的身份：

- RLE.wiki的站长有且只有北雁云依和全程未出现的HalfSweet，只有她们二位有权利决定这个PR的最终去留，如何修改，以及是否合并。
![image](https://github.com/project-trans/RLE-wiki/assets/23723294/7114cfb8-351f-4882-8ce8-12dd2f0af1c8)
- 其余人为RLE.wiki或其他站点编辑，或与Project Trans有友好合作的其他外部组织的专家，或热心路人，我们感谢她们参与讨论。但同时需要向你提醒，所有人的审阅都是建议而不是要求，我们没有关闭这个PR，即证明我们需要更多时间和精力用于讨论如何更好的修改你的PR的内容。我们自始至终没有要求你必须修改，或者威胁你不予收录的意图。

如果审稿过程对你带来了不好的体验，我代表所有人向你道歉。我忠心希望所有人都能在审稿和交流的过程中和平愉快，而不是不友好的言论甚至用偏激的言论威胁对方。而你如此对待一些没有权利决定这个PR去留的热心人士，是没有任何意义的。

2024-04-12 08:57 UTC, Cryolitia commented
使用来自内部的时间线记录补全缺失的对话并对此做出解释和回复：
![image](https://github.com/project-trans/RLE-wiki/assets/23723294/075b404c-d201-4492-8118-c07790440723)
这段话中的「他们」，指的是这个PR的作者，把这个PR投稿到清蒸，指的是把你写的RLE经验投稿到清蒸。因为我个人观点认为，您的这部分言论更符合清蒸协会的政治立场而不是我们的。清蒸协会更为提倡女性的刻板印象规训，成功的脱跨入顺等达尔文主义。RLE.wiki是一个开放包容的多元化平台，我们不预设您的「成功RLE」的经验具有先进性和优越性，而只是就事论事的审阅稿件，您的此段言论对审阅此PR并无任何意义。

> 请自便
如我所说，我的原意是建议您将您成功的融入顺性别女性群体并以此自豪的此段经验投稿到清蒸协会，我们无意代您投稿。

2024-04-12 09:30 UTC, Cryolitia commented
> 其实我是能感觉到你们有在很矛盾的，特别是在前两天的事件过后，我看到了你们的声明，所谓的只是一个切面而非全貌就是如此。

RLE.wiki 在推特上的那篇推文是我独自起草和发布的，未提交RLE.wiki讨论，未经过任何其他人批准，如果这篇推文引起任何问题由我一人承担。

> 我觉得我们比你们想得更清楚，我们无法得到每一个人的认可。
> 但实际上你们一边说着这只是一部分人，一边却要求要（也许）每个人都能接受的官方观点。

我们的成员和审稿人不可避免地有自己的观点，我一开始也只是尽量多找审稿人一起讨论内容是否适宜以及如何去进行合并。我相信更多的观点碰撞交流可以给出一个更合适的各方都可接受的解决方案，没说让你直接和几个特定的热心审稿人吵起来。诚然，我承认我们的审稿人也有一些偏激的言论，但是如我上一条所说，我们之中也没有人威胁不予收录或者关闭PR，大家都还是一个希望能够去讨论和妥善解决问题的态度，至少我是这样去希望的。

> 实际上没有观点是不可能的，我们无法做到。或者换言之，在这些文档中每一句话都是观点。

对，这我承认，每一句话确实都是观点，wiki不可能完全中立毫无政治立场。但是我们不希望出现太多远远偏离主线而且引起很多争议的观点。例如，「成为一个真正的女孩子应该如何化妆」是可以讨论的而且大概率可以最终接受的。但是「女性主义」「男权社会的利益交换」就和RLE这个主题离题万里了。我们此前的建议是希望您能够保留与主线内容联系较为紧密的观点，同时将部分离题万里的观点无论对错都去别的平台讨论比如推特。

> 为什么我的大学同学会期待我写一个很完整的经验文档？那是因为我的RLE简直是成功的没边了，如果不考虑自谦的问题，在跨性别女生中就没有几个能比我融入得更好的。（我们其他作者也属于融入比较好的人）

好的，我们现在知道您自认为您的融入很成功了，但是这似乎与我们的审稿毫无关系。

> 难道你们真的觉得rle只是改变形象的事情？

如我们反复强调的，RLE的目标是成为最好的自己，而不是别的什么东西。因此每个人RLE的过程和目的都千差万别，对有些人来说改变形象是最重要的而对有些人来说是最不重要的。

> 如果我只想写一些普通的，不带我的特色的东西，那这个系列的文档将根本不会存在（毕竟，那样的东西谁都可以写）

对我们承认所以如我们前面所说「我们希望您在保留自身行文风格的前提下，删去与主线偏差过大的内容而保留联系紧密的内容，这部分内容中是可以有个人观点而且很多观点是可以保留的。」

> 说实话，我是很久没有见过系统性的这类指南了。那本《好想做个女孩子——伪娘养成手册》是在我初中的时候进入我的百度网盘的，非常遗憾。但是这么多年了仍然有很多人在看那个。mtf.wiki上面的内容至今为止仍是漏洞百出，

如果您对MtFwiki有任何意见或建议我们会帮您转达，MtFwiki确实很多内容许久无人维护，我们也没有能力让内容自己从土里长出来，但我个人毫不谦虚的姑且认为尚不至于到漏洞百出的程度。请允许我对您的这段评论表达悲伤和遗憾。

rle.wiki上的内容更是少得可怜。

> 所以我们尝试开设了 Fashion 栏目，试图开拓更广泛的内容。但是我们不可避免地在此类议题上缺乏成熟的经验，对此我表达我歉意。

我们选择了rle.wiki只是因为这个网站看起来比较美观，功能还算好用罢了。

> 我代表全体前端开发组成员向您传达我们忠心的感谢，感谢您喜欢我们设计的网站（鞠躬）。

> 如果你们认为是这样的话，我们就真的去其他地方发了。并且我们会在后续版本中标注“本系列内容根据知识共享许可协议向除了project-trans项目有关的任何实体授权”。

我们网站建设的目的是更好的服务跨性别群体，不是和推特或者其他什么实体比谁的有用信息多。我们这样认为是因为我们真的觉得推特是一个更好的讨论女性主义相关政治议题的地方，而RLEwiki更多的是倾向更具体的穿搭梳妆相关的指导。如您愿意的话您也可以将更具体部分的操作发在RLEwiki同时去推特畅所欲言您的政治观点。

> 以上，请各位reviewer重新考虑是否要撤回前面的commit

我个人从这句话中读出了威胁的意味，你可以声明不接受reviewer的意见或继续与reviewer讨论如何修改，而不是要求review撤回评论。即使是我或站长都无权要求任何人撤回评论

> 你可以在这里发表非观点性质的教程，但是至少我不接受灌输观点性质的内容。你可以投稿那部分具体细分的教程到 RLE Wiki。我们也不奢求“系统性的 RLE 教程”。如果你希望发表大量观点性质的东西，你可以自行发布。发布和以后可能收到的评价都和 Project-Trans 没有关系

很遗憾的是，发表这段评论的人无权关闭或决定不接受你的PR，如前所述，决定权在站长。可能他的语气或措辞使您产生了误解，在此我致以诚挚的歉意。

总结：您依然可以修改后重新投递本文章，综合前述评论观点，我以个人身份建议您可以仅删除大段与RLE主题无关的女性主义论述，而保留具体的RLE部分并在其中包含您的观点。

2024-04-12 09:32 UTC, Cryolitia commented
最后，将由于锁定话题发表到 #306 的部分讨论搬运过来：

> 我觉得 #285 中包含了太多的「观点」性的内容，有一些我能认可，有一些我持怀疑态度。朋友们的对这些观点也各有各的看法。这让我开始思考一个问题：
> 
> > RLE Wiki 是什么？RLE Wiki 到底应该做什么？
> 
> 我认为 RLE Wiki 应该保持其中立性，不应该被用来输出观点，无论这个观点被项目维护方支持或是反对 —— 而应该作为一个能包容各种观点，能给各种不同人的合理诉求提供指导的地方。
> 
> 还引申出来另一个我想到的问题 ——
> 
> > 写出「输出争议性观点的」内容的作者一定是有意的吗？可能未必。
> 
> 很多人受限于人生阅历和生活环境，并不能（或者没有意识）去站在中立的视角上去叙事，他们可能认为「这个世界就是这样的」。我希望审校者们能够意识到，并且理解作者的这种行为。本篇中就有很多「无意中带着观点」的表述，比如，跨性别语境下「真正的女孩子」就是一个典型的例子。
> 
> 我希望，审校者能够了解各种观点，在遇到（无论有意地还是无意地）持与自己相悖的观点时，能够站在作者的观点视角上去理解作者想要说明的事情，提出修改建议，必要时需要大段的改写，而不是一味的对观点相悖的表达进行批判。说到底，观点有争议，但观点没有对错 —— 甲之蜜糖乙之砒霜，同一个观点，对有些人的实践指导作用是正面的，而对有些人的实践指导作用是负面的。
> 
> 就拿「融入顺性别」这一点来说：
> 
> * 有些人以融入为方针而行事，最后转变非常成功；
> * 而有些人因为主观或客观的原因，即使尽力，也没法做到融入；
> * 也有些人认为，不需要融入也能生活的很好；
> * 更有些人认为，自己就要与别人不同，融入了是不好的事情。
> 
> 观点本身没有对错，错的是把这样一种只适用于一部分人的观点，在这样一个面向公众，泛用化，（被很多人认为）权威的平台上进行输出，这是不合适的。
> 
> 所以我认为，如何对「包含争议性观点」的内容进行处理，是一个值得探讨的问题。我个人的想法是，任何这类的观点，都需要有 disclaimer 来给读者做出必要的解释 —— 甚至可以单开一区，专门有一些内容来解释这些观点的不同。