Fafu的trans指南
project-trans/RLE-wiki pull request #288
Opened 2024-03-19 05:59 UTC by kunkunreal666

一点信息，祝你成为自己

2024-03-19 06:50 UTC, BeiyanYunyi requested changes
有些链接会出错，小改一下

2024-03-19 06:50 UTC, BeiyanYunyi commented on docs/campus/FAFU.md
> +[福建农林大学]((https://www.fafu.edu.cn/))（Fujian Agriculture and Forestry University,FAFU）福建农林大学是是农业农村部、国家林业和草原局与福建省人民政府共建高校，入选福建省一流大学建设高校、“双一流”建设A类高校。下属一所独立学院福建农林大学金山学院。
```suggestion
[福建农林大学](https://www.fafu.edu.cn/)（Fujian Agriculture and Forestry University,FAFU）福建农林大学是是农业农村部、国家林业和草原局与福建省人民政府共建高校，入选福建省一流大学建设高校、“双一流”建设A类高校。下属一所独立学院福建农林大学金山学院。
```

2024-03-19 06:50 UTC, BeiyanYunyi commented on docs/campus/FAFU.md
> +> （福州市大学生医保参考2023年政策文件：https://www.fuzhou.gov.cn/zfxxgkzl/szfbmjxsqxxgk/szfbmxxgk/fzsylbzj/zfxxgkml/zcwj/202306/t20230629_4629171.htm）
```suggestion
> （福州市大学生医保参考 [2023 年政策文件](https://www.fuzhou.gov.cn/zfxxgkzl/szfbmjxsqxxgk/szfbmxxgk/fzsylbzj/zfxxgkml/zcwj/202306/t20230629_4629171.htm)）
```

2024-03-19 06:50 UTC, BeiyanYunyi commented on docs/campus/FAFU.md
> +（https://hqc.fafu.edu.cn/31/31/c12279a340273/page.htm）<br>
```suggestion
```

2024-03-19 06:50 UTC, BeiyanYunyi commented on docs/campus/FAFU.md
> +> 以下内容来源于《福建农林大学学生日常医疗补助经费管理暂行办法》<br>
```suggestion
> 以下内容来源于[《福建农林大学学生日常医疗补助经费管理暂行办法》](https://hqc.fafu.edu.cn/31/31/c12279a340273/page.htm)<br>
```

2024-04-06 11:41 UTC, clansty commented
是不是该合并了

2024-04-06 11:53 UTC, BeiyanYunyi approved these changes

2024-04-06 11:54 UTC, BeiyanYunyi commented
> 是不是该合并了

我又改了一点，你 Review 下，好了就合吧

2024-04-06 11:57 UTC, clansty requested changes

2024-04-06 11:57 UTC, clansty commented on docs/campus/FAFU.md
> +给 mtf 的建议：如果自己相对还算 pass,可以按小男娘的方式告知但不出柜
```suggestion
给 MtF 的建议：如果自己相对还算 pass，可以按小男娘的方式告知但不出柜  
```

2024-04-06 11:57 UTC, clansty commented on docs/campus/FAFU.md
> +给 ftm 的建议：建议按 T 的方式告知舍友吧
```suggestion
给 FtM 的建议：建议按 T 的方式告知舍友吧  
```

2024-04-06 12:11 UTC, Cryolitia approved these changes
不太喜欢emoji，不过TL;AP

2024-04-06 13:57 UTC, HalfSweet approved these changes

2024-04-10 03:29 UTC, BeiyanYunyi approved these changes

2024-04-10 03:30 UTC, merged