更新CUC医保报销相关内容
project-trans/RLE-wiki pull request #291
Opened 2024-03-21 16:27 UTC by Wishing-Qi

2024-03-21 16:36 UTC, Cryolitia requested changes

2024-03-21 16:36 UTC, Cryolitia commented on docs/campus/CUC.md
> +
```suggestion
> 来自一名双A顺男的补充：
> 
> 挂号时请直接说明所要挂的科室而不要说因为xx疾病来的，转诊单在内科即可开到，向医生说明情况即可，收费处的工作人员在碰到不常见疾病的时候会多问，很尴尬。本人在校医院内科以成人多动症的名义顺利开具了去往回龙观医院的转诊单（当时还未确诊ADHD，且医生似乎对ADHD很陌生）并顺利拿到了医保报销（特需挂号费与药费不报，可与医生商量将处方改为公费来避免问题）。
>
> 如果因同种疾病在北医六院，安定医院与回龙观医院就诊（尚不确定去往不同医院是否需要重新开具转诊单，且不确定其他医院是否适用，可在就诊时向校医院医生询问），可在报销时在二楼公疗办和医生提出申请并登记（笔者尚未因此被约谈），后续不需重新开具转诊单，直接携带处方底方与发票到二楼公疗办报销即可（电子发票需要在医院自助机自行打印）。
>
> 公费医疗报销并不限时，可在校医院工作时间随时携带上述材料去往校医院二楼公疗办提交报销，另请注意：寒暑假期间发生的校外医疗费用不在公费医疗报销范围内，但是听说有某个基金会部分报销学生的医疗费用，尚不清楚具体流程与保密细则。
>
> 校医院周四上午有精神科门诊，据说药费比转诊后报销的要便宜，但尚不确定具体药品名单与是否能凭其他医院的处方拿到药，笔者近期会去试试。

```

2024-03-23 13:32 UTC, Cryolitia approved these changes

2024-03-23 13:41 UTC, HalfSweet approved these changes

2024-03-23 13:41 UTC, merged