更新中国地质大学（北京）相关情况
project-trans/RLE-wiki pull request #332
Opened 2024-05-02 17:02 UTC by HalfSweet

2024-05-02 17:04 UTC, BeiyanYunyi approved these changes

2024-05-04 18:42 UTC, Cryolitia requested changes

2024-05-04 18:42 UTC, Cryolitia commented on docs/campus/CUGB.md
> +> 涉及宿舍与基础设施的内容，可参照 (https://colleges.chat/universities/zhong-guo-di-zhi-da-xue-bei-jing/)
```suggestion
> 涉及宿舍与基础设施的内容，可参照 [大学生活质量指北](https://colleges.chat/universities/zhong-guo-di-zhi-da-xue-bei-jing/)
```

2024-05-04 18:42 UTC, Cryolitia commented on docs/campus/CUGB.md
> +本校人际环境对于跨性别群体的友好程度一般。校内对 LGBT 的不友善现象多发。笔者曾经因穿裙子外出，而被其他同学以侮辱性言论攻击。一些老师也对跨性别群体发表过攻击性言论。少数教师与年轻学工对跨儿的包容程度相当高。
```suggestion
> 本校人际环境对于跨性别群体的友好程度一般。校内对 LGBT 的不友善现象多发。笔者曾经因穿裙子外出，而被其他同学以侮辱性言论攻击。一些老师也对跨性别群体发表过攻击性言论。少数教师与年轻学工对跨儿的包容程度相当高。

```

2024-05-04 18:42 UTC, Cryolitia commented on docs/campus/CUGB.md
> +学校的院系与专业可在学校官网查看（https://www.cugb.edu.cn/jxdw.jhtml）。总体而言，地大的专业大多围绕地球科学开展课程，绝大部分专业需要出野实习。各院系对 LGBT 的态度有较大差异，具体情况待完善。
```suggestion
学校的院系与专业可在 [学校官网](https://www.cugb.edu.cn/jxdw.jhtml) 。总体而言，地大的专业大多围绕地球科学开展课程，绝大部分专业需要出野实习。各院系对 LGBT 的态度有较大差异，具体情况待完善。
```

2024-05-05 05:25 UTC, Cryolitia commented on docs/campus/CUGB.md
> +学校的院系与专业可在 [学校官网](https://www.cugb.edu.cn/jxdw.jhtml) 。总体而言，地大的专业大多围绕地球科学开展课程，绝大部分专业需要出野实习。各院系对 LGBT 的态度有较大差异，具体情况待完善。
```suggestion
学校的院系与专业可在 [学校官网](https://www.cugb.edu.cn/jxdw.jhtml) 查看。总体而言，地大的专业大多围绕地球科学开展课程，绝大部分专业需要出野实习。各院系对 LGBT 的态度有较大差异，具体情况待完善。
```

2024-05-05 05:26 UTC, Cryolitia approved these changes

2024-05-05 05:26 UTC, merged