docs(campus/NUFE): 📝 Add docs/campus/NUFE.md
project-trans/RLE-wiki pull request #394
Opened 2024-09-01 12:12 UTC by LeeGuanLi

iss：南京财经大学 #386
看见有个闲置issues顺手给传了）

2024-09-01 12:21 UTC, BeiyanYunyi approved these changes

2024-09-01 12:22 UTC, BeiyanYunyi requested changes

2024-09-01 12:22 UTC, BeiyanYunyi commented on docs/campus/NUFE.md
> +笔者设立有[nufe.wiki](nufe.wiki)网站并在网站上留有联系方式 可通过此渠道或笔者的QQ1694865639联系到笔者。
```suggestion
笔者设立有[nufe.wiki](https://nufe.wiki)网站并在网站上留有联系方式 可通过此渠道或笔者的QQ1694865639联系到笔者。
```

2024-09-01 12:48 UTC, BeiyanYunyi approved these changes

2024-09-04 19:08 UTC, Cryolitia approved these changes

2024-09-04 19:08 UTC, merged