docs(fashion/be-a-girl): update archive links
project-trans/RLE-wiki pull request #402
Opened 2024-09-05 13:54 UTC by Leetfs

issues：链接死链 #400
添加链接存档

2024-09-05 13:56 UTC, BeiyanYunyi requested changes

2024-09-05 13:56 UTC, BeiyanYunyi commented on docs/fashion/be-a-girl/2.md
> +  <br>存档链接：https://web.archive.org/web/20200327200353/https://qxzh.github.io/collection/
```suggestion
  翻译版: https://qxzh.github.io/collection/  
  存档链接：https://web.archive.org/web/20200327200353/https://qxzh.github.io/collection/
```

2024-09-05 13:56 UTC, BeiyanYunyi commented on docs/fashion/be-a-girl/2.md
> +  <br>存档链接：https://web.archive.org/web/20240301211346/https://adlib1.net/ws2/h-life/page-85
```suggestion
  原版: https://adlib1.net/ws2/h-life/page-85  
  存档链接：https://web.archive.org/web/20240301211346/https://adlib1.net/ws2/h-life/page-85
```

2024-09-05 13:56 UTC, BeiyanYunyi commented on docs/fashion/be-a-girl/2.md
> +  <br>存档链接：https://web.archive.org/web/20201110103537/https://qxzh.github.io/translation/
```suggestion
  参与翻译: https://qxzh.github.io/translation/  
  存档链接：https://web.archive.org/web/20201110103537/https://qxzh.github.io/translation/
```

2024-09-05 14:12 UTC, BeiyanYunyi commented
在前一行末添加两个空格 `  `，或反斜杠 `\` 即可换行。

2024-09-05 14:14 UTC, Leetfs commented
> 在前一行末添加两个空格 ` `，或反斜杠 `\` 即可换行。

@BeiyanYunyi 感谢）
奇怪的知识又增加了

2024-09-05 14:15 UTC, CoelacanthusHex commented
> @BeiyanYunyi md文档中，跨段落自动换行（中间隔一个空行），同段落需使用br标签进行换行

Markdown 里标准的换行语法是行尾连续两个空格或者反斜杠

https://spec.commonmark.org/0.31.2/#hard-line-break

2024-09-05 14:17 UTC, Leetfs commented
> > @BeiyanYunyi md文档中，跨段落自动换行（中间隔一个空行），同段落需使用br标签进行换行
> 
> Markdown 里标准的换行语法是行尾连续两个空格或者反斜杠
> 
> https://spec.commonmark.org/0.31.2/#hard-line-break

@CoelacanthusHex 
原来如此，我一直以为是用br换行））

2024-09-05 14:19 UTC, Leetfs commented
@BeiyanYunyi 转为`\`了，辛苦重新审一下~
（空格会被插件误格式化掉）

2024-09-05 14:34 UTC, BeiyanYunyi approved these changes

2024-09-05 15:11 UTC, Leetfs commented
顺手测试了下[be a girl 系列](https://rle.wiki/fashion/be-a-girl/index)内的所有链接，其中部分知乎链接和https://www.translives.net/网站下的链接均失效且在Wayback Machine和archive.ph内均无存档，能找到存档的我都补了

2024-09-05 15:14 UTC, Leetfs commented
> 顺手测试了下[be a girl 系列](https://rle.wiki/fashion/be-a-girl/index)内的所有链接，其中部分知乎链接和 `https://www.translives.net/` 网站下的链接均失效，且在Wayback Machine和 archive.ph 内均无存档，能找到存档的我都补了

2024-09-08 07:46 UTC, Cryolitia approved these changes

2024-09-08 07:46 UTC, Cryolitia commented
CC @jinyuzu99

2024-09-16 17:23 UTC, merged