新增字数和预计阅读时间，优化作者信息显示逻辑
project-trans/RLE-wiki pull request #411
Opened 2024-09-11 11:39 UTC by Leetfs

Preview URL:  https://8f990c19.rle-wiki-7lk.pages.dev

测试效果：

<img width="492" alt="image" src="https://github.com/user-attachments/assets/183ca072-6c95-4fe8-96e0-92fd65e39efa">

<img width="571" alt="image" src="https://github.com/user-attachments/assets/3217a329-97a9-4cb2-9ceb-f62b1cfccac5">

2024-09-11 15:43 UTC, BeiyanYunyi requested changes

2024-09-11 15:43 UTC, BeiyanYunyi commented on packages/vitepress-theme-project-trans/src/components/ReadingTime.vue
> +  const contentElement = document.querySelector('.VPContent') // 获取文档内容的 DOM 元素
这一行会导致构建时报 document is not defined 错误。

仍在寻找构建时而非运行时统计字数的方案。

2024-09-11 16:04 UTC, BeiyanYunyi approved these changes

2024-09-12 11:29 UTC, Cryolitia approved these changes

2024-09-12 11:30 UTC, Cryolitia approved these changes

2024-09-12 11:30 UTC, merged