新增 insert-word-count.js 并 重构 ReadingTime.vue 以获取更准确的文档字数
project-trans/RLE-wiki pull request #414
Opened 2024-09-12 16:36 UTC by Leetfs

## 运行流程
- 引入 `gray-matter` ，构建时读取并解析每个 Markdown 文件，分离出其 Frontmatter 和正文内容
- 根据正文内容计算字数，并将字数信息作为 `wordCount` 字段插入到文档的 Frontmatter 中
- `ReadingTime` 组件获取文档 Frontmatter 中的字数信息，并计算阅读时长

2024-09-12 16:41 UTC, Leetfs commented
Preview URL:  https://a3c3c8ba.rle-wiki-7lk.pages.dev

2024-09-12 16:41 UTC, BeiyanYunyi requested changes
不好。会造成大量更改。与之相比还不如在浏览器端跑。

2024-09-12 16:44 UTC, BeiyanYunyi commented
VitePress 有提供在构建时查看文档内容并修改 frontmatter 的 [API](https://vitepress.dev/zh/reference/site-config#transformhead)。我个人认为在 dev 模式下字数不可见是可以接受的。

2024-09-12 16:45 UTC, Leetfs commented
这两天我翻翻）

2024-09-12 16:58 UTC, Leetfs commented
简要看了下，应该是中的（）
明天测测看

2024-09-13 07:43 UTC, BeiyanYunyi requested changes

2024-09-13 07:43 UTC, BeiyanYunyi commented on docs/.vitepress/config.ts
> +});
这一部分应该挪到 genConfig 里

2024-09-13 11:51 UTC, Leetfs commented
此问题已解决，测试url：https://b838f4ce.rle-wiki-7lk.pages.dev/

CC @BeiyanYunyi

2024-09-16 16:25 UTC, BeiyanYunyi approved these changes

2024-09-16 17:23 UTC, Cryolitia approved these changes

2024-09-16 17:23 UTC, merged