docs(campus/NJMU): 添加南京医科大学
project-trans/RLE-wiki pull request #418
Opened 2024-09-15 09:29 UTC by Leetfs

2024-09-16 17:25 UTC, Cryolitia requested changes

2024-09-16 17:25 UTC, Cryolitia commented on docs/campus/NJMU.md
> +邮箱：1838208958@qq.com
```suggestion
### 千月

- QQ：1838208958
- 邮箱：<1838208958@qq.com>
```

2024-09-17 08:09 UTC, HalfSweet commented on docs/campus/NJMU.md
> +目前（2024）所有本科生，（部分？）研究生均入学南京江宁校区，位于南京江宁大学城。校北门有公交站，南门有南京地铁1号线，可直达南京市中心（约1h）。学校附近一站路的距离有两个美食娱乐城，基本都是大学城学生课余汇聚之处。
此处地址应当添加高德地图地点链接

2024-09-18 05:33 UTC, BeiyanYunyi commented on docs/campus/NJMU.md
> +order: 2
```suggestion
```

2024-09-18 05:40 UTC, BeiyanYunyi approved these changes

2024-09-19 23:26 UTC, Cryolitia approved these changes

2024-09-19 23:26 UTC, merged