黑龙江职业学院
project-trans/RLE-wiki pull request #441
Opened 2024-09-29 20:23 UTC by Oriyukiiii

2024-09-29 20:27 UTC, Leetfs requested changes

2024-09-29 20:27 UTC, Leetfs commented on docs/campus/HLJP.md
> +
```suggestion
title: 黑龙江职业学院
author: 浅羽织雪
```

2024-09-29 20:34 UTC, Leetfs approved these changes

2024-09-29 20:39 UTC, Leetfs requested changes

2024-09-29 20:39 UTC, Leetfs commented on docs/campus/HLJP.md
> +- twitter：@Oriyukiiiii
```suggestion

## 投稿人联系方式

### 浅羽织雪
- twitter：@Oriyukiiiii
```

2024-09-29 21:05 UTC, Leetfs approved these changes

2024-09-30 00:35 UTC, Leetfs approved these changes

2024-10-01 03:43 UTC, AnnaBeiyan commented on docs/campus/HLJP.md
> +| 军训凭医疗材料减免 |  ✓  |            淘宝做个病历免训  |
是不是没必要在这里提淘宝啊。这只是建议。

2024-10-01 07:22 UTC, AnnaBeiyan approved these changes

2024-10-01 07:22 UTC, merged