Update:天津机电职业技术学院
project-trans/RLE-wiki pull request #457
Opened 2024-10-19 10:19 UTC by mis1042

2024-10-19 10:35 UTC, Leetfs requested changes

2024-10-19 10:35 UTC, Leetfs commented on docs/campus/TVCME.md
> +寝室单个电器限制功率308w、1400毫安，一间宿舍总限制功率1799w、8181毫安。
您好，我想核实下确定电流限制为1400mA么？
现在主流手机适配器输入电流为2A，230W的笔记本适配器输入电流约为2.5A-3A，1A=1000mA

2024-10-19 10:55 UTC, SASAS2 commented on docs/campus/TVCME.md
> +寝室单个电器限制功率308w、1400毫安，一间宿舍总限制功率1799w、8181毫安。
![Uploading mmexport1728187544884.jpg…]()
这是来自宿管的图，具体情况我不清楚，反正正常都能用

2024-10-19 10:59 UTC, Leetfs commented on docs/campus/TVCME.md
> +寝室单个电器限制功率308w、1400毫安，一间宿舍总限制功率1799w、8181毫安。
您的图似乎没有被上传

2024-10-19 11:00 UTC, SASAS2 commented on docs/campus/TVCME.md
> +寝室单个电器限制功率308w、1400毫安，一间宿舍总限制功率1799w、8181毫安。
![mmexport1728187544884](https://github.com/user-attachments/assets/c91b9741-f784-4a51-a6a9-2a43ec870b26)

2024-10-19 11:01 UTC, mis1042 commented on docs/campus/TVCME.md
> +寝室单个电器限制功率308w、1400毫安，一间宿舍总限制功率1799w、8181毫安。
![Image_1729335612605](https://github.com/user-attachments/assets/53052da1-bd7b-4f06-b712-93f77573fed2)

2024-10-19 11:17 UTC, SASAS2 commented on docs/campus/TVCME.md
> +寝室单个电器限制功率308w、1400毫安，一间宿舍总限制功率1799w、8181毫安。
如果引起争议，这个毫安也可以删掉，220v只有乘这个电流才是这个瓦数，这个宿管的图也是这样的，但是为什么适配器都能正常用，这我就不清楚了

2024-10-19 11:20 UTC, Leetfs commented on docs/campus/TVCME.md
> +寝室单个电器限制功率308w、1400毫安，一间宿舍总限制功率1799w、8181毫安。
感谢贡献~

2024-10-19 11:20 UTC, Leetfs approved these changes

2024-10-22 05:26 UTC, AnnaBeiyan approved these changes

2024-10-22 05:48 UTC, merged