更新 2.md 细节
project-trans/RLE-wiki pull request #461
Opened 2024-10-28 02:27 UTC by ChisakaKanako

2024-10-28 02:32 UTC, Leetfs approved these changes

2024-10-28 08:08 UTC, Cryolitia requested changes
这是个人署名的有限共享作品，请联系原作者二创授权。

2024-10-28 19:20 UTC, Leetfs commented
CC @Lhcfl

请问是否允许二创，以及需要更新文章版权区内的链接么(404)

2024-10-29 03:23 UTC, Lhcfl commented
这篇文章的无图版本不是写的 CC-BY-SA 3.0 吗为什么要找我问二创授权（？

limelight我创作的这篇文章上面的插图不准无授权转载不准二创，但文字是  CC-BY-SA 3.0 请按规范随意使用

2024-10-29 03:24 UTC, BeiyanYunyi commented
> 这是个人署名的有限共享作品，请联系原作者二创授权。

CC-BY-SA，没有 ND，可以自行衍生。已与原作者确认。

2024-10-29 03:25 UTC, Cryolitia commented
请把自己加入作者，或在作者栏内添加匿名

2024-10-29 03:38 UTC, closed without merging