ZUEL.md
project-trans/RLE-wiki pull request #472
Opened 2024-10-30 13:50 UTC by kbya

新增大学介绍

2024-10-30 13:56 UTC, kbya commented
天语法写错了怎么改换行全都换错了（）
应该查一下的。。。

2024-10-30 14:07 UTC, Leetfs commented
> 天语法写错了怎么改换行全都换错了（）
> 应该查一下的。。。

可以直接在你 fork 出的仓库内更改

2024-10-30 15:01 UTC, Leetfs commented on docs/campus/ZUEL.md
> +校医院条件较差，只能做肝功、肾功等基础检查（一周只有两天，要在9点之前挂号请医生开具）。//> 激素六项未知。笔者两次开具六项均失败，医生回答“因为是自费所以医院没准备这个项目”。但也有顺性别女性在妇科开出激素六项的传闻。//关于医保，校医院医保自动报销。但是校医院只能处理简单疾病，而且有时由于各种原因本来可以做的检验检查都做不了。校外就医需要校医开据转诊单，留好票据，每季度统一报销一次。校医经
请问 `//` 和 `//>` 的预期效果是什么（？
不会操作的话我可以帮您修改。

2024-10-30 16:52 UTC, Leetfs requested changes

2024-10-30 16:52 UTC, Leetfs commented on docs/campus/ZUEL.md
> +军训一般三周，不要求剪头发，免训难度未知，半训很简单（只要有诊断证明即可，前往救护点开假条，隔一段时间需要重开一次），半训作息和军训相同，但不需训练，在阴凉处静坐即可。\ > 另有传闻首义军训会更加严格。
## 换行方法

在行末添加 两个空格 或 \

### 示例

我是第一句话\
我是第二句话

## 分段方法

在两个段落间隔一个空行

### 示例

我是第一段

我是第二段

2024-10-30 16:54 UTC, Leetfs commented on docs/campus/ZUEL.md
> +军训一般三周，不要求剪头发，免训难度未知，半训很简单（只要有诊断证明即可，前往救护点开假条，隔一段时间需要重开一次），半训作息和军训相同，但不需训练，在阴凉处静坐即可。\ > 另有传闻首义军训会更加严格。
> ## 换行方法
> 
> 在行末添加 两个空格 或 \
> 
> ### 示例
> 
> 我是第一句话\
> 我是第二句话
> 
> ## 分段方法
> 
> 在两个段落间隔一个空行
> 
> ### 示例
> 
> 我是第一段
> 
> 我是第二段
> 
> 
> 

您可以参考此语法进行实现，另：`引用` 格式为在行开头使用 `>`

2024-10-31 00:51 UTC, Leetfs approved these changes

2024-10-31 03:23 UTC, BeiyanYunyi approved these changes

2024-10-31 03:23 UTC, merged