Update NJU.md
project-trans/RLE-wiki pull request #479
Opened 2024-11-09 10:50 UTC by njujimbo

增加校内qq群联系方式

2024-11-09 10:56 UTC, Leetfs approved these changes

2024-11-09 14:38 UTC, BeiyanYunyi requested changes

2024-11-09 14:38 UTC, BeiyanYunyi commented on docs/campus/NJU.md
> +呢喃目前有一个校内同类聊天的qq群，若想加群可戳我qq确认身份后拉入。
```suggestion
若有信息更新不及时还请多多谅解，欢迎各位校友通过以上联系方式进行投稿！

呢喃目前有一个校内同类聊天的qq群，若想加群可戳我qq确认身份后拉入。
```

2024-11-11 01:59 UTC, BeiyanYunyi approved these changes

2024-11-11 01:59 UTC, merged