Update SWU.md
project-trans/RLE-wiki pull request #501
Opened 2024-12-13 12:05 UTC by Ketelee

更正信息

2024-12-13 12:10 UTC, Cryolitia commented on docs/campus/SWU.md
> +|    军训协商减免    |   ✓  |   有正当理由可以直接免除
这里格式疑似有问题，哪个维护者处理下或者等我回家

2024-12-13 12:25 UTC, Leetfs commented on docs/campus/SWU.md
> +|    军训协商减免    |   ✓  |   有正当理由可以直接免除
修了

2024-12-13 12:25 UTC, Leetfs approved these changes

2024-12-13 12:29 UTC, Leetfs requested changes

2024-12-13 12:29 UTC, Leetfs commented on docs/campus/SWU.md
> +  - 蘑菇 花盆
```suggestion
  - 蘑菇
  - 花盆
```

如要添加新作者，请使用此方法。

参考链接：https://rle.wiki/contributor-guide/campus

2024-12-13 12:57 UTC, Ketelee reviewed
请问可以看见这个吗

2024-12-13 12:59 UTC, Leetfs approved these changes

2024-12-16 15:09 UTC, BeiyanYunyi approved these changes

2024-12-16 15:09 UTC, merged