Add CUIT
project-trans/RLE-wiki pull request #510
Opened 2024-12-23 11:32 UTC by Rosmontis2333

2024-12-23 11:49 UTC, Leetfs requested changes

2024-12-23 11:49 UTC, Leetfs commented on docs/campus/cuit.md
> +- E-Mail:<rosmontis233@hotmail.com>
```suggestion

|        项目        | 情况 |     备注     |
| :----------------: | :--: | :----------: |
|      宿舍独卫      |  ✓   |              |
|      宿舍独浴      |  ✓   |              |
|     第三卫生间     |  ✗   |              |
|    军训协商减免    |  ?   |              |
| 军训凭医疗材料减免 |  ✓   |              |
|    军训不管头发    |  ✓   |               |
|    体育协商减免    |  ?   |              |
| 体育凭医疗材料减免 |  ✓   |              |
|      医保使用      |  ?   |              |
|     校医院服务     |   ?  |              |

## 概述

[成都信息工程大学](https://www.cuit.edu.cn/)(Chengdu University of Information Technology),成都信息工程大学是四川省人民政府和中国气象局、国家统计局共建、四川省重点发展的省属普通本科院校。

## 地理位置及交通

- 航空港校区位于[四川省 成都市 西南航空港经济开发区 学府路一段24号](https://www.amap.com/place/B001C0650L)，一般来说为理工类学科学生日常学习的校区，校门口有公交车站，可以坐公交去附近的顺风地铁站，也可以走着去（大约两公里多），从顺风到成都市中心（天府广场）大概半小时。

- 龙泉校区位于[成都市 龙泉驿区 阳光城 幸福路10号](https://www.amap.com/place/B001C06VLJ)，一般来说为文科类学生日常学习的校区，笔者对该校区的情况并不了解。

## 军训与体育

### 军训

军训不管头发，持有医疗证明可以免训，训练在上午和晚上进行，强度看教官个人，甚至存在有的教官管的很松你一天都不用去，但要注意关注及时交材料表格之类的文件

### 体育课

不分性别，体育课分数包含考勤(20%)体测(20%)校园跑(10%)期末考核(50%)

~~不会真有人自己跑校园跑吧~~

## 宿舍情况与基础设施

六人间，独立卫浴，两个上下铺+两个上床下桌，所以说三个人用一张床的桌子，非常挤。

学校实际上不管校外居住(理论上要申请走读，但是不管)，想出去住可以直接走，附近小区很多，大概700左右就能租到一个单间。

希望有同类来和笔者合租（

## 医疗资源

报销需先在校医院开转诊单，笔者没有尝试过

## LGBT 友善梗概

目前看几个技术类社团实验室友好气氛较好

### 跨性别分布情况

笔者本人只认识毕业了的学姐（

## 投稿人联系方式

### 贡献者姓名

- Telegram:<https://t.me/Rosmontis233>
- Twitter:<https://x.com/Rosmontis233>
- E-Mail:<rosmontis233@hotmail.com>
```
感谢贡献，有一点点小问题

- 使用✓而不是根号
- 将模板自带的info块移除
- 修正联系方式下的贡献者姓名

我已为您制作修改建议，您可以直接点击下面的按钮应用更改~

2024-12-31 07:17 UTC, Leetfs commented
该PR已搁置一周，我先提交了

2024-12-31 07:18 UTC, Leetfs approved these changes

2024-12-31 08:21 UTC, HalfSweet approved these changes

2024-12-31 08:21 UTC, merged