更新线条腿部曲线研究文章
project-trans/RLE-wiki pull request #515
Opened 2024-12-28 09:54 UTC by dongguacute

2024-12-28 10:03 UTC, Leetfs requested changes
感谢贡献~
- 请使用纯英文路径，url 中的中文会被转义，不利于分享及索引。例如此页的 URL 编码为<https://eb5736f2.rle-wiki-e0r.pages.dev/fashion/%E8%BA%AB%E4%BD%93%E6%9B%B2%E7%BA%BF%E7%BA%BF%E6%9D%A1/legs>
- RLE.wiki 面向全体跨性别者，请不要假定读者的性别。建议优化概述。

2024-12-28 10:03 UTC, dongguacute commented
好的

2024-12-31 08:50 UTC, HalfSweet commented
非常感谢你提交的PR，并为文档做出的贡献。但是经过我们审阅之后发现，您的文章中似乎存在一些LLM生成的片段，这可能会导致一些读者的反感与不解。并且您的文章中对于步骤的原理解释似乎也有一些欠缺，这同样会导致读者的困惑。

基于这些原因，我们决定暂时不合并此次PR。不过，我们非常欢迎你未来提交更多富有价值和深度的修改，帮助我们共同提高文档质量。

再次感谢你的努力和贡献，期待你的下一次提交！

2024-12-31 08:50 UTC, closed without merging

2024-12-31 09:17 UTC, Cryolitia commented
@HalfSweet 我不反对 HalfSweet 作为 RLE.wiki 站长作出的决定