更新腿部线条研究（身体线条研究）
project-trans/RLE-wiki pull request #516
Opened 2024-12-31 12:01 UTC by dongguacute

我声明，我确实是使用了LLM但LLM仅为搜索工具，帮助我收集资料，这次我解释清楚了全部原因，望通过，我非常乐意与Project-Trans共享TransSoul｜曲线视觉实验室的研究成果

2024-12-31 12:55 UTC, dongguacute commented
哦对了，新年快乐

2024-12-31 13:05 UTC, Cryolitia commented
@dongguacute 新年快乐

2025-01-01 03:32 UTC, P-ZH commented
请问这个内容和跨性别有什么关系吗

2025-01-01 05:23 UTC, dongguacute commented
@P-ZH 对于跨性别来说，比如mtf，她想要成为一个女孩子就要有女孩子的身体线条，而本研究通过研究身体曲线，并且研究出调整的方法

2025-01-01 05:38 UTC, P-ZH requested changes
1. 不明白本文所示的这种腿型和形成这种腿型的（可能）方式对于女性倾向跨性别者的 RLE 有何帮助。我没见过几个拥有这种腿型的女性，拥有这样腿型的似乎更容易是男性（因为雌激素会促使脂肪向大腿和小腿囤积）。本教程可能会为女性倾向跨性别者造成不必要的心理负担甚至加重性别焦虑。
2. 即便我们一定要按照某种来源不明且和性别肯定或 RLE 无关的标准为腿型进行评价，本文所示的腿型也似乎不符合正常腿型标准。比如，说明中提到小腿「内侧则为直线型」，示意图中两腿的小腿肌肉更是完全没有贴合（但膝盖和脚踝似乎可以贴合）：这其实是比较典型的 XO 型腿（小腿外翻）症状。这种腿型和性别认同毫无关系，且追求这种腿型很可能给当事人造成安全和健康隐患。

基于以上原因，个人认为本文内容似乎更接近某种特殊 xp，而不是 RLE；建议 close pull request。

2025-01-01 05:38 UTC, dongguacute commented
正如wiki名字叫rlewiki，是为了rle而生的，那么在rle的过程中为了让旁人看着像，所以我通过研究身体曲线，毕竟人类是通过参考物来判断的

2025-01-01 05:39 UTC, P-ZH commented
> 正如wiki名字叫rlewiki，是为了rle而生的，那么在rle的过程中为了让旁人看着像，所以我通过研究身体曲线，毕竟人类是通过参考物来判断的

https://github.com/project-trans/RLE-wiki/pull/516#pullrequestreview-2526773670

2025-01-01 05:40 UTC, dongguacute commented
不是的，我的那个基本是根据标准的腿形扣图扣出来的线条，可能我手画的没那么好

2025-01-01 05:46 UTC, dongguacute commented
@P-ZH 图是我从网上找了张图片勾勒出来的，可能没那么好，我改一下，但是我的解决方法没错吧？

2025-01-01 05:50 UTC, yunwei37 commented
作为一个局外人，我会认为某些解决方案可能是不太合适的（？

 rle 的内容不能和常识以及生活经验相违背，打扮也不应该有如此严苛的要求，从另一个角度来说，很多人就是穿中性或者男装看起来像帅气大姐姐并且有助于 pass，过于女性化的打扮反而看起来像男娘

2025-01-01 05:52 UTC, dongguacute commented
是但是为了解决焦虑问题，这是唯一的办法

2025-01-01 05:52 UTC, dongguacute commented
从根源解决问题

2025-01-01 05:52 UTC, dongguacute commented
我找了不止一两个去看都是有缝隙的，是因为膝盖顶住了

2025-01-01 05:53 UTC, yunwei37 commented
> 是但是为了解决焦虑问题，这是唯一的办法

也许这个说法对于你来说是正确的，但是可能并不具有普适性，所以可能不一定适合作为 wiki（？

2025-01-01 05:54 UTC, Cryolitia requested changes
文本篇幅过短且质量不佳，疑似AI写作

2025-01-01 05:55 UTC, P-ZH commented
> @P-ZH 图是我从网上找了张图片勾勒出来的，可能没那么好，我改一下，但是我的解决方法没错吧？

显然我说的就是你的解决方法有错，因为你的图和你给出的「教程」实际上是一致的，即小腿内侧呈直线型，而这种审美一方面过于小众，一方面可能会损害当事人健康，因此我质疑你提出此类健康建议的资质和在医学领域的相关知识储备。截至目前，你没有回答或证明：
1. 为什么这种腿部线条是属于「女性」的（为何它独属于女性或大部分女性）
2. 这种身体线条是否是健康的
3. 你提出的相关指导方案是否可以在保证当事人身体健康的情况下达成你在示意图中展示的效果（考虑到你在 1 和 2 中展现出的生理知识匮乏）。

2025-01-01 05:56 UTC, closed without merging